# Generated by Django 5.2.17 on 2026-08-13 10:04

import django.db.models.deletion
import kurslar.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurslar', '0002_lessonresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options', models.JSONField(help_text='List of {"text": "...", "is_correct": true/false}')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_questions', to='kurslar.course')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(default=kurslar.models.generate_certificate_id, max_length=9, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='kurslar.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
    ]
