# Generated by Django 5.2.17 on 2026-08-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurslar', '0003_finaltestquestion_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/media/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='finaltestquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/images/'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/images/'),
        ),
        migrations.AlterField(
            model_name='finaltestquestion',
            name='options',
            field=models.JSONField(help_text='List of {"text": "...", "is_correct": true/false, "image_url": "..."}'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='options',
            field=models.JSONField(help_text='List of {"text": "...", "is_correct": true/false, "image_url": "..."}'),
        ),
    ]
