# Generated by Django 5.2.17 on 2026-08-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurslar', '0004_uploadedmedia_finaltestquestion_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaltestquestion',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
