# Generated by Django 5.2.17 on 2026-08-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurslar', '0005_alter_finaltestquestion_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finaltestquestion',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='testquestion',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='finaltestquestion',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
