# Generated by Django 5.2.17 on 2026-08-13 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurslar', '0008_module_lesson_module'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set(),
        ),
    ]
