# Generated by Django 5.2.17 on 2026-09-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurslar', '0009_alter_lesson_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('kompyuter_asoslari', 'Kompyuter asoslari'), ('grafik_dizayn', 'Grafik dizayn'), ('dasturlash', 'Dasturlash'), ('suniy_intellekt', "Sun'iy intellekt"), ('robototexnika', 'Robototexnika'), ('boshqa', 'Boshqa')], default='boshqa', max_length=50),
        ),
    ]
