# Generated by Django 5.2.17 on 2026-09-06 17:40

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('kurslar', '0010_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
