# Generated by Django 5.2.17 on 2026-09-07 07:44

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('kurslar', '0011_course_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='author_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='author_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
