# Generated by Django 5.2.17 on 2026-09-11 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurslar', '0012_course_author_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('is_passed', models.BooleanField(default=False)),
                ('details', models.JSONField(help_text='List of user answers and correctness')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='kurslar.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_passed', models.BooleanField(default=False)),
                ('score_percentage', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('in_progress', 'Jarayonda'), ('failed_retry_required', 'Qayta tayyorlanish kerak'), ('passed', "Muvaffaqiyatli o'tgan")], default='in_progress', max_length=30)),
                ('ai_diagnostic_feedback', models.TextField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='kurslar.module')),
                ('required_lessons_to_repeat', models.ManyToManyField(blank=True, to='kurslar.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'module')},
            },
        ),
    ]
