--
-- PostgreSQL database dump
--

\restrict spTXnpfcyI0JlSNiNdWepWVJ5aeWG4EhhxDTjt9is77X6BOZaluGf8UuywIyU8d

-- Dumped from database version 17.10
-- Dumped by pg_dump version 17.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: django_site; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_site (
    id integer NOT NULL,
    domain character varying(100) NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.django_site OWNER TO postgres;

--
-- Name: django_site_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_site ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_site_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kurslar_certificate; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.kurslar_certificate (
    id bigint NOT NULL,
    certificate_id character varying(9) NOT NULL,
    issued_at timestamp with time zone NOT NULL,
    score integer NOT NULL,
    course_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.kurslar_certificate OWNER TO postgres;

--
-- Name: kurslar_certificate_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.kurslar_certificate ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kurslar_certificate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kurslar_course; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.kurslar_course (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    thumbnail character varying(100),
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.kurslar_course OWNER TO postgres;

--
-- Name: kurslar_course_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.kurslar_course ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kurslar_course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kurslar_customuser; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.kurslar_customuser (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    phone character varying(15) NOT NULL,
    full_name character varying(150) NOT NULL,
    birth_date date,
    gender character varying(10) NOT NULL,
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.kurslar_customuser OWNER TO postgres;

--
-- Name: kurslar_customuser_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.kurslar_customuser_groups (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.kurslar_customuser_groups OWNER TO postgres;

--
-- Name: kurslar_customuser_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.kurslar_customuser_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kurslar_customuser_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kurslar_customuser_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.kurslar_customuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kurslar_customuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kurslar_customuser_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.kurslar_customuser_user_permissions (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.kurslar_customuser_user_permissions OWNER TO postgres;

--
-- Name: kurslar_customuser_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.kurslar_customuser_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kurslar_customuser_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kurslar_finaltestattempt; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.kurslar_finaltestattempt (
    id bigint NOT NULL,
    score integer NOT NULL,
    is_passed boolean NOT NULL,
    details jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    course_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.kurslar_finaltestattempt OWNER TO postgres;

--
-- Name: kurslar_finaltestattempt_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.kurslar_finaltestattempt ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kurslar_finaltestattempt_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kurslar_finaltestquestion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.kurslar_finaltestquestion (
    id bigint NOT NULL,
    question_text text NOT NULL,
    options jsonb NOT NULL,
    course_id bigint NOT NULL,
    image character varying(500),
    "order" integer NOT NULL,
    CONSTRAINT kurslar_finaltestquestion_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.kurslar_finaltestquestion OWNER TO postgres;

--
-- Name: kurslar_finaltestquestion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.kurslar_finaltestquestion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kurslar_finaltestquestion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kurslar_lesson; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.kurslar_lesson (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    "order" integer NOT NULL,
    youtube_video_id character varying(50) NOT NULL,
    content text NOT NULL,
    course_id bigint NOT NULL,
    module_id bigint,
    CONSTRAINT kurslar_lesson_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.kurslar_lesson OWNER TO postgres;

--
-- Name: kurslar_lesson_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.kurslar_lesson ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kurslar_lesson_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kurslar_lessonresource; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.kurslar_lessonresource (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    file character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    lesson_id bigint NOT NULL
);


ALTER TABLE public.kurslar_lessonresource OWNER TO postgres;

--
-- Name: kurslar_lessonresource_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.kurslar_lessonresource ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kurslar_lessonresource_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kurslar_module; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.kurslar_module (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    "order" integer NOT NULL,
    course_id bigint NOT NULL,
    CONSTRAINT kurslar_module_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.kurslar_module OWNER TO postgres;

--
-- Name: kurslar_module_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.kurslar_module ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kurslar_module_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kurslar_testattempt; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.kurslar_testattempt (
    id bigint NOT NULL,
    score integer NOT NULL,
    is_passed boolean NOT NULL,
    details jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    lesson_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.kurslar_testattempt OWNER TO postgres;

--
-- Name: kurslar_testattempt_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.kurslar_testattempt ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kurslar_testattempt_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kurslar_testquestion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.kurslar_testquestion (
    id bigint NOT NULL,
    question_text text NOT NULL,
    options jsonb NOT NULL,
    lesson_id bigint NOT NULL,
    image character varying(500),
    "order" integer NOT NULL,
    CONSTRAINT kurslar_testquestion_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.kurslar_testquestion OWNER TO postgres;

--
-- Name: kurslar_testquestion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.kurslar_testquestion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kurslar_testquestion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kurslar_uploadedmedia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.kurslar_uploadedmedia (
    id bigint NOT NULL,
    file character varying(100) NOT NULL,
    uploaded_at timestamp with time zone NOT NULL
);


ALTER TABLE public.kurslar_uploadedmedia OWNER TO postgres;

--
-- Name: kurslar_uploadedmedia_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.kurslar_uploadedmedia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kurslar_uploadedmedia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kurslar_userprogress; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.kurslar_userprogress (
    id bigint NOT NULL,
    is_unlocked boolean NOT NULL,
    is_passed boolean NOT NULL,
    score integer NOT NULL,
    lesson_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.kurslar_userprogress OWNER TO postgres;

--
-- Name: kurslar_userprogress_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.kurslar_userprogress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kurslar_userprogress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add site	6	add_site
22	Can change site	6	change_site
23	Can delete site	6	delete_site
24	Can view site	6	view_site
25	Can add custom user	7	add_customuser
26	Can change custom user	7	change_customuser
27	Can delete custom user	7	delete_customuser
28	Can view custom user	7	view_customuser
29	Can add course	8	add_course
30	Can change course	8	change_course
31	Can delete course	8	delete_course
32	Can view course	8	view_course
33	Can add module	9	add_module
34	Can change module	9	change_module
35	Can delete module	9	delete_module
36	Can view module	9	view_module
37	Can add lesson	10	add_lesson
38	Can change lesson	10	change_lesson
39	Can delete lesson	10	delete_lesson
40	Can view lesson	10	view_lesson
41	Can add test question	11	add_testquestion
42	Can change test question	11	change_testquestion
43	Can delete test question	11	delete_testquestion
44	Can view test question	11	view_testquestion
45	Can add user progress	12	add_userprogress
46	Can change user progress	12	change_userprogress
47	Can delete user progress	12	delete_userprogress
48	Can view user progress	12	view_userprogress
49	Can add lesson resource	13	add_lessonresource
50	Can change lesson resource	13	change_lessonresource
51	Can delete lesson resource	13	delete_lessonresource
52	Can view lesson resource	13	view_lessonresource
53	Can add final test question	14	add_finaltestquestion
54	Can change final test question	14	change_finaltestquestion
55	Can delete final test question	14	delete_finaltestquestion
56	Can view final test question	14	view_finaltestquestion
57	Can add certificate	15	add_certificate
58	Can change certificate	15	change_certificate
59	Can delete certificate	15	delete_certificate
60	Can view certificate	15	view_certificate
61	Can add uploaded media	16	add_uploadedmedia
62	Can change uploaded media	16	change_uploadedmedia
63	Can delete uploaded media	16	delete_uploadedmedia
64	Can view uploaded media	16	view_uploadedmedia
65	Can add test attempt	17	add_testattempt
66	Can change test attempt	17	change_testattempt
67	Can delete test attempt	17	delete_testattempt
68	Can view test attempt	17	view_testattempt
69	Can add final test attempt	18	add_finaltestattempt
70	Can change final test attempt	18	change_finaltestattempt
71	Can delete final test attempt	18	delete_finaltestattempt
72	Can view final test attempt	18	view_finaltestattempt
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	sites	site
7	kurslar	customuser
8	kurslar	course
9	kurslar	module
10	kurslar	lesson
11	kurslar	testquestion
12	kurslar	userprogress
13	kurslar	lessonresource
14	kurslar	finaltestquestion
15	kurslar	certificate
16	kurslar	uploadedmedia
17	kurslar	testattempt
18	kurslar	finaltestattempt
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-08-16 18:16:27.112883+05
2	contenttypes	0002_remove_content_type_name	2026-08-16 18:16:27.131949+05
3	auth	0001_initial	2026-08-16 18:16:27.229219+05
4	auth	0002_alter_permission_name_max_length	2026-08-16 18:16:27.24122+05
5	auth	0003_alter_user_email_max_length	2026-08-16 18:16:27.254876+05
6	auth	0004_alter_user_username_opts	2026-08-16 18:16:27.266714+05
7	auth	0005_alter_user_last_login_null	2026-08-16 18:16:27.279189+05
8	auth	0006_require_contenttypes_0002	2026-08-16 18:16:27.281266+05
9	auth	0007_alter_validators_add_error_messages	2026-08-16 18:16:27.30123+05
10	auth	0008_alter_user_username_max_length	2026-08-16 18:16:27.3121+05
11	auth	0009_alter_user_last_name_max_length	2026-08-16 18:16:27.325571+05
12	auth	0010_alter_group_name_max_length	2026-08-16 18:16:27.340992+05
13	auth	0011_update_proxy_permissions	2026-08-16 18:16:27.353502+05
14	auth	0012_alter_user_first_name_max_length	2026-08-16 18:16:27.366196+05
15	kurslar	0001_initial	2026-08-16 18:16:27.561427+05
16	admin	0001_initial	2026-08-16 18:16:27.621567+05
17	admin	0002_logentry_remove_auto_add	2026-08-16 18:16:27.641471+05
18	admin	0003_logentry_add_action_flag_choices	2026-08-16 18:16:27.661291+05
19	kurslar	0002_lessonresource	2026-08-16 18:16:27.70845+05
20	kurslar	0003_finaltestquestion_certificate	2026-08-16 18:16:27.815226+05
21	kurslar	0004_uploadedmedia_finaltestquestion_image_and_more	2026-08-16 18:16:27.864962+05
22	kurslar	0005_alter_finaltestquestion_image_and_more	2026-08-16 18:16:27.89358+05
23	kurslar	0006_alter_finaltestquestion_options_and_more	2026-08-16 18:16:27.944801+05
24	kurslar	0007_finaltestattempt_testattempt	2026-08-16 18:16:28.057347+05
25	kurslar	0008_module_lesson_module	2026-08-16 18:16:28.167547+05
26	kurslar	0009_alter_lesson_unique_together_and_more	2026-08-16 18:16:28.234708+05
27	sessions	0001_initial	2026-08-16 18:16:28.262632+05
28	sites	0001_initial	2026-08-16 18:16:28.27409+05
29	sites	0002_alter_domain_unique	2026-08-16 18:16:28.287618+05
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
drzj6lgb1ibmngq434ayq35drtvkcvt1	.eJxVjMsOwiAQAP9lz4YApTx69O43kAV2pWpoUtqT8d9Nkx70OjOZN0Tctxr3TmucC0wwwOWXJcxPaocoD2z3ReSlbeucxJGI03ZxWwq9rmf7N6jYK0wQePCU5cg6ocPkpS5WBykDowvEKbPy1pKx2RltjJEjGS4KldaJkRA-X_DyOF4:1wuM2o:6P0ftVG1DTRfdyhli_2-eRJCscjZUrhUz6kv5Jolkx0	2026-08-27 08:23:50.771+05
i1tr092je24amsrfw9sx4xy98hge8r7n	.eJxVjEEOwiAQAP-yZ0NgoUB79O4bCLtQqRpISnsy_t006UGvM5N5Q4j7VsLe8xqWBBNouPwyivzM9RDpEeu9CW51WxcSRyJO28Wtpfy6nu3foMReYAJCrQYyhmdM0koymKQhpdh5hRg9j8oMmDRa9k652bH2SHaUbIkyEXy-wc83VA:1wuRKe:ngVYo2aiLjZ9b2KbbywGWb6xWSb4hsu5Z9p8G3LjGqQ	2026-08-27 14:02:36.9+05
s01l6ihc4kbr5nyyr9ofh75z86ojzer2	.eJxVjEEOwiAQAP-yZ0OQhbr06N03NAssUjWQlPZk_Ltp0oNeZybzhom3tUxbl2WaE4yAcPplgeNT6i7Sg-u9qdjqusxB7Yk6bFe3luR1Pdq_QeFeYATtMERtaGDnzSUyabGGUhJMmIPTMYj2OKDzGonI-kjnnF3Oki0RB_h8AdY8N-c:1wuRKf:lG5azi_7U3QMueG83g9YQlKkhlRzS1os117PNw0fsdk	2026-08-27 14:02:37.603+05
\.


--
-- Data for Name: django_site; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_site (id, domain, name) FROM stdin;
1	example.com	example.com
\.


--
-- Data for Name: kurslar_certificate; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.kurslar_certificate (id, certificate_id, issued_at, score, course_id, user_id) FROM stdin;
1	NPSE-E1G9	2026-08-13 17:44:16.945+05	100	1	2
2	3MEP-KX65	2026-08-13 21:30:45.713+05	100	1	3
\.


--
-- Data for Name: kurslar_course; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.kurslar_course (id, title, description, thumbnail, created_at) FROM stdin;
1	Test uchun	Nimadir ta'rif	courses/thumbnails/Rasul_Bahriddinov-Screenshot_2026-08-09_172138.png	2026-08-13 14:24:29.128+05
2	Kompyuter savodxonligi	Kompyuterda ishlashni o'rganasiz	courses/thumbnails/2gis.jpg	2026-08-13 21:49:58.503+05
3	Frontend	fsgdfhf	courses/thumbnails/Screenshot_2026-08-16_170746.png	2026-08-16 18:01:12.139+05
\.


--
-- Data for Name: kurslar_customuser; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.kurslar_customuser (id, password, last_login, is_superuser, phone, full_name, birth_date, gender, is_active, is_staff, date_joined) FROM stdin;
1	pbkdf2_sha256$1000000$5hhaqTUQUel3yWuMkZGEUh$fv2ViPq51e+owHuGvB6gYH6n3UejrKtPInsAyKRoaLE=	\N	f	998123456789	Test uchun	2026-08-19	erkak	t	f	2026-08-13 08:21:53.772+05
2	pbkdf2_sha256$1000000$5jNrAsIhlWWmTeuKchd6An$bOOltWh8eLe9Rn+baR4oQJIFAcnl5aQCW884C+3yl7E=	2026-08-13 14:02:37.593+05	t	+998901234567	Super Admin	\N		t	t	2026-08-13 08:22:44.697+05
3	pbkdf2_sha256$1000000$1vbh1KV1eTtxYzCqS25okc$WP8eR2t3Wri8ecfqyi5QLUBqdWYtJe9La6t7dyHTbt4=	\N	f	998987654321	Ismoilova Xilola	2000-06-13	ayol	t	f	2026-08-13 21:12:24.851+05
\.


--
-- Data for Name: kurslar_customuser_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.kurslar_customuser_groups (id, customuser_id, group_id) FROM stdin;
\.


--
-- Data for Name: kurslar_customuser_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.kurslar_customuser_user_permissions (id, customuser_id, permission_id) FROM stdin;
\.


--
-- Data for Name: kurslar_finaltestattempt; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.kurslar_finaltestattempt (id, score, is_passed, details, created_at, course_id, user_id) FROM stdin;
1	100	t	[{"is_correct": true, "question_id": 1, "question_text": "aaaa", "selected_option": 0}, {"is_correct": true, "question_id": 2, "question_text": "b", "selected_option": 0}, {"is_correct": true, "question_id": 3, "question_text": "O'zbekistonning poytaxti qayer?", "selected_option": 2}]	2026-08-13 21:30:45.697+05	1	3
\.


--
-- Data for Name: kurslar_finaltestquestion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.kurslar_finaltestquestion (id, question_text, options, course_id, image, "order") FROM stdin;
1	aaaa	[{"text": "1", "is_correct": true}, {"text": "2", "is_correct": false}]	1	\N	0
2	b	[{"text": "2", "is_correct": true}, {"text": "222", "is_correct": false}, {"text": "2", "is_correct": false}]	1	\N	1
3	O'zbekistonning poytaxti qayer?	[{"text": "Samarqand", "image_url": "", "is_correct": false}, {"text": "Buxoro", "image_url": "", "is_correct": false}, {"text": "Toshkent", "image_url": "", "is_correct": true}, {"text": "Namangan", "image_url": "", "is_correct": false}]	1	\N	2
\.


--
-- Data for Name: kurslar_lesson; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.kurslar_lesson (id, title, "order", youtube_video_id, content, course_id, module_id) FROM stdin;
1	1. Kirish darsi	1	https://www.youtube.com/watch?v=6Z-sUu1tgvc	Dars haqida qo'shimcha ma'lumot bo'ladi	1	\N
2	2-dars	2	https://www.youtube.com/watch?v=qSSOa7AjkGs	Dars haqida qo'shimcha ma'lumotlar. Dars haqida qo'shimcha ma'lumotlar. Dars haqida qo'shimcha ma'lumotlar. Dars haqida qo'shimcha ma'lumotlar. Dars haqida qo'shimcha ma'lumotlar.	1	\N
3	3-dars	3	https://www.youtube.com/watch?v=8r5Bvv7GiC4	https://www.youtube.com/watch?v=8r5Bvv7GiC4https://www.youtube.com/watch?v=8r5Bvv7GiC4https://www.youtube.com/watch?v=8r5Bvv7GiC4https://www.youtube.com/watch?v=8r5Bvv7GiC4https://www.youtube.com/watch?v=8r5Bvv7GiC4https://www.youtube.com/watch?v=8r5Bvv7GiC4https://www.youtube.com/watch?v=8r5Bvv7GiC4https://www.youtube.com/watch?v=8r5Bvv7GiC4	1	\N
4	4-dars	4	https://www.youtube.com/watch?v=8r5Bvv7GiC4	ssssssss	1	\N
5	5-dars	5	https://www.youtube.com/watch?v=8r5Bvv7GiC4	https://www.youtube.com/watch?v=8r5Bvv7GiC4	1	\N
6	1. Kirish	2	https://www.youtube.com/watch?v=8r5Bvv7GiC4	askjd hskfdsgfiudgugfigifd	2	1
7	2. nimadir	1	https://www.youtube.com/watch?v=8r5Bvv7GiC4	sajdfdsdfd	2	1
8	45. jsbfsbf shdhjf	3	https://www.youtube.com/watch?v=8r5Bvv7GiC4	safsdf	2	2
9	trryrt	1	youtube.com	yu	3	3
\.


--
-- Data for Name: kurslar_lessonresource; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.kurslar_lessonresource (id, title, file, created_at, lesson_id) FROM stdin;
1	Savollar	lessons/resources/Word_Kahoot_Test_30_Savol.xlsx	2026-08-13 14:48:16.535+05	1
\.


--
-- Data for Name: kurslar_module; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.kurslar_module (id, title, "order", course_id) FROM stdin;
1	1. Boshlang'ich	2	2
2	Namuna	1	2
3	asrwetrey	1	3
\.


--
-- Data for Name: kurslar_testattempt; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.kurslar_testattempt (id, score, is_passed, details, created_at, lesson_id, user_id) FROM stdin;
1	66	f	[{"is_correct": false, "question_id": 1, "question_text": "dasdfsfsd", "selected_option": 1}, {"is_correct": true, "question_id": 2, "question_text": "sdsfsdf", "selected_option": 1}, {"is_correct": true, "question_id": 8, "question_text": "O'zbekistonning poytaxti qayer?", "selected_option": 2}, {"is_correct": true, "question_id": 9, "question_text": "O'zbekistonning poytaxti qayer?", "selected_option": 2}, {"is_correct": true, "question_id": 10, "question_text": "O'zbekistonning poytaxti qayer?", "selected_option": 2}, {"is_correct": false, "question_id": 11, "question_text": "savol", "selected_option": 3}]	2026-08-13 19:21:39.526+05	1	1
2	66	f	[{"is_correct": true, "question_id": 1, "question_text": "dasdfsfsd", "selected_option": 0}, {"is_correct": false, "question_id": 2, "question_text": "sdsfsdf", "selected_option": 0}, {"is_correct": true, "question_id": 8, "question_text": "O'zbekistonning poytaxti qayer?", "selected_option": 2}, {"is_correct": true, "question_id": 9, "question_text": "O'zbekistonning poytaxti qayer?", "selected_option": 2}, {"is_correct": true, "question_id": 10, "question_text": "O'zbekistonning poytaxti qayer?", "selected_option": 2}, {"is_correct": false, "question_id": 11, "question_text": "savol", "selected_option": 3}]	2026-08-13 19:21:51.421+05	1	1
3	66	f	[{"is_correct": false, "question_id": 1, "question_text": "dasdfsfsd", "selected_option": 1}, {"is_correct": false, "question_id": 2, "question_text": "sdsfsdf", "selected_option": 0}, {"is_correct": true, "question_id": 8, "question_text": "O'zbekistonning poytaxti qayer?", "selected_option": 2}, {"is_correct": true, "question_id": 9, "question_text": "O'zbekistonning poytaxti qayer?", "selected_option": 2}, {"is_correct": true, "question_id": 10, "question_text": "O'zbekistonning poytaxti qayer?", "selected_option": 2}, {"is_correct": true, "question_id": 11, "question_text": "savol", "selected_option": 0}]	2026-08-13 19:22:04.34+05	1	1
4	50	f	[{"is_correct": false, "question_id": 1, "question_text": "dasdfsfsd", "selected_option": 2}, {"is_correct": false, "question_id": 2, "question_text": "sdsfsdf", "selected_option": 0}, {"is_correct": true, "question_id": 8, "question_text": "O'zbekistonning poytaxti qayer?", "selected_option": 2}, {"is_correct": true, "question_id": 9, "question_text": "O'zbekistonning poytaxti qayer?", "selected_option": 2}, {"is_correct": true, "question_id": 10, "question_text": "O'zbekistonning poytaxti qayer?", "selected_option": 2}, {"is_correct": false, "question_id": 11, "question_text": "savol", "selected_option": 1}]	2026-08-13 19:22:21.463+05	1	1
5	83	t	[{"is_correct": true, "question_id": 1, "question_text": "dasdfsfsd", "selected_option": 0}, {"is_correct": false, "question_id": 2, "question_text": "sdsfsdf", "selected_option": 2}, {"is_correct": true, "question_id": 8, "question_text": "O'zbekistonning poytaxti qayer?", "selected_option": 2}, {"is_correct": true, "question_id": 9, "question_text": "O'zbekistonning poytaxti qayer?", "selected_option": 2}, {"is_correct": true, "question_id": 10, "question_text": "O'zbekistonning poytaxti qayer?", "selected_option": 2}, {"is_correct": true, "question_id": 11, "question_text": "savol", "selected_option": 0}]	2026-08-13 19:22:44.114+05	1	1
6	100	t	[{"is_correct": true, "question_id": 3, "question_text": "a", "selected_option": 0}, {"is_correct": true, "question_id": 4, "question_text": "a", "selected_option": 0}]	2026-08-13 19:22:54.518+05	2	1
7	83	t	[{"is_correct": true, "question_id": 1, "question_text": "dasdfsfsd", "selected_option": 0}, {"is_correct": false, "question_id": 2, "question_text": "sdsfsdf", "selected_option": 0}, {"is_correct": true, "question_id": 8, "question_text": "O'zbekistonning poytaxti qayer?", "selected_option": 2}, {"is_correct": true, "question_id": 9, "question_text": "O'zbekistonning poytaxti qayer?", "selected_option": 2}, {"is_correct": true, "question_id": 10, "question_text": "O'zbekistonning poytaxti qayer?", "selected_option": 2}, {"is_correct": true, "question_id": 11, "question_text": "savol", "selected_option": 0}]	2026-08-13 21:25:44.491+05	1	3
8	100	t	[{"is_correct": true, "question_id": 3, "question_text": "a", "selected_option": 0}, {"is_correct": true, "question_id": 4, "question_text": "a", "selected_option": 0}]	2026-08-13 21:30:03.389+05	2	3
9	100	t	[{"is_correct": true, "question_id": 5, "question_text": "121212", "selected_option": 0}]	2026-08-13 21:30:12.68+05	3	3
10	100	t	[{"is_correct": true, "question_id": 6, "question_text": "aa", "selected_option": 0}]	2026-08-13 21:30:23.088+05	4	3
11	100	t	[{"is_correct": true, "question_id": 7, "question_text": "a", "selected_option": 0}]	2026-08-13 21:30:30.888+05	5	3
\.


--
-- Data for Name: kurslar_testquestion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.kurslar_testquestion (id, question_text, options, lesson_id, image, "order") FROM stdin;
1	dasdfsfsd	[{"text": "111", "is_correct": true}, {"text": "2222", "is_correct": false}, {"text": "333", "is_correct": false}]	1	\N	0
2	sdsfsdf	[{"text": "1", "is_correct": false}, {"text": "2322", "is_correct": true}, {"text": "3", "is_correct": false}]	1	\N	0
3	a	[{"text": "a", "is_correct": true}, {"text": "aa", "is_correct": false}, {"text": "aaa", "is_correct": false}]	2	\N	0
4	a	[{"text": "aa", "is_correct": true}, {"text": "aaa", "is_correct": false}, {"text": "aaaa", "is_correct": false}]	2	\N	0
5	121212	[{"text": "12121", "is_correct": true}, {"text": "212121", "is_correct": false}, {"text": "21212", "is_correct": false}]	3	\N	0
6	aa	[{"text": "a", "is_correct": true}, {"text": "a", "is_correct": false}, {"text": "a", "is_correct": false}]	4	\N	0
7	a	[{"text": "a", "is_correct": true}, {"text": "aa", "is_correct": false}]	5	\N	0
8	O'zbekistonning poytaxti qayer?	[{"text": "Samarqand", "image_url": "", "is_correct": false}, {"text": "Buxoro", "image_url": "", "is_correct": false}, {"text": "Toshkent", "image_url": "", "is_correct": true}, {"text": "Namangan", "image_url": "", "is_correct": false}]	1	\N	0
9	O'zbekistonning poytaxti qayer?	[{"text": "Samarqand", "image_url": "", "is_correct": false}, {"text": "Buxoro", "image_url": "", "is_correct": false}, {"text": "Toshkent", "image_url": "", "is_correct": true}, {"text": "Namangan", "image_url": "", "is_correct": false}]	1	\N	0
10	O'zbekistonning poytaxti qayer?	[{"text": "Samarqand", "image_url": "", "is_correct": false}, {"text": "Buxoro", "image_url": "", "is_correct": false}, {"text": "Toshkent", "image_url": "", "is_correct": true}, {"text": "Namangan", "image_url": "", "is_correct": false}]	1	\N	0
11	savol	[{"text": "121", "image_url": "", "is_correct": true}, {"text": "ffgergr", "image_url": "", "is_correct": false}, {"text": "sghfvdsfg", "image_url": "", "is_correct": false}, {"text": "jygsd", "image_url": "", "is_correct": false}]	1	\N	0
12	NIma bu	[{"text": "Ali", "image_url": "", "is_correct": true}, {"text": "Shu", "image_url": "http://localhost:8000/media/uploads/media/Azizbek_Safarov-%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA_%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0_2026-08-09_152030.png", "is_correct": false}]	6	http://localhost:8000/media/uploads/media/Rasul_Bahriddinov-Screenshot_2026-08-09_152802.png	0
\.


--
-- Data for Name: kurslar_uploadedmedia; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.kurslar_uploadedmedia (id, file, uploaded_at) FROM stdin;
1	uploads/media/Rasul_Bahriddinov-Screenshot_2026-08-09_152802.png	2026-08-13 21:52:10.824+05
2	uploads/media/Azizbek_Safarov-Снимок_экрана_2026-08-09_152030.png	2026-08-13 21:52:22.116+05
3	uploads/media/Screenshot_2026-08-16_170746.png	2026-08-16 18:01:37.147+05
\.


--
-- Data for Name: kurslar_userprogress; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.kurslar_userprogress (id, is_unlocked, is_passed, score, lesson_id, user_id) FROM stdin;
1	t	t	100	1	2
2	t	t	100	2	2
3	t	t	100	3	2
4	t	t	100	4	2
5	t	t	100	5	2
6	t	t	83	1	1
7	t	t	100	2	1
8	t	f	0	3	1
9	t	t	83	1	3
10	t	t	100	2	3
11	t	t	100	3	3
12	t	t	100	4	3
13	t	t	100	5	3
14	t	f	0	6	2
15	t	f	0	7	2
16	t	f	0	7	3
17	t	f	0	8	3
18	t	f	0	8	2
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 72, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 18, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 29, true);


--
-- Name: django_site_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_site_id_seq', 1, true);


--
-- Name: kurslar_certificate_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.kurslar_certificate_id_seq', 2, true);


--
-- Name: kurslar_course_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.kurslar_course_id_seq', 3, true);


--
-- Name: kurslar_customuser_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.kurslar_customuser_groups_id_seq', 1, false);


--
-- Name: kurslar_customuser_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.kurslar_customuser_id_seq', 3, true);


--
-- Name: kurslar_customuser_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.kurslar_customuser_user_permissions_id_seq', 1, false);


--
-- Name: kurslar_finaltestattempt_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.kurslar_finaltestattempt_id_seq', 1, true);


--
-- Name: kurslar_finaltestquestion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.kurslar_finaltestquestion_id_seq', 3, true);


--
-- Name: kurslar_lesson_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.kurslar_lesson_id_seq', 9, true);


--
-- Name: kurslar_lessonresource_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.kurslar_lessonresource_id_seq', 1, true);


--
-- Name: kurslar_module_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.kurslar_module_id_seq', 3, true);


--
-- Name: kurslar_testattempt_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.kurslar_testattempt_id_seq', 11, true);


--
-- Name: kurslar_testquestion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.kurslar_testquestion_id_seq', 12, true);


--
-- Name: kurslar_uploadedmedia_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.kurslar_uploadedmedia_id_seq', 3, true);


--
-- Name: kurslar_userprogress_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.kurslar_userprogress_id_seq', 18, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: django_site django_site_domain_a2e37b91_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_domain_a2e37b91_uniq UNIQUE (domain);


--
-- Name: django_site django_site_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_pkey PRIMARY KEY (id);


--
-- Name: kurslar_certificate kurslar_certificate_certificate_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_certificate
    ADD CONSTRAINT kurslar_certificate_certificate_id_key UNIQUE (certificate_id);


--
-- Name: kurslar_certificate kurslar_certificate_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_certificate
    ADD CONSTRAINT kurslar_certificate_pkey PRIMARY KEY (id);


--
-- Name: kurslar_certificate kurslar_certificate_user_id_course_id_5c19714d_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_certificate
    ADD CONSTRAINT kurslar_certificate_user_id_course_id_5c19714d_uniq UNIQUE (user_id, course_id);


--
-- Name: kurslar_course kurslar_course_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_course
    ADD CONSTRAINT kurslar_course_pkey PRIMARY KEY (id);


--
-- Name: kurslar_customuser_groups kurslar_customuser_groups_customuser_id_group_id_1bcc6c98_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_customuser_groups
    ADD CONSTRAINT kurslar_customuser_groups_customuser_id_group_id_1bcc6c98_uniq UNIQUE (customuser_id, group_id);


--
-- Name: kurslar_customuser_groups kurslar_customuser_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_customuser_groups
    ADD CONSTRAINT kurslar_customuser_groups_pkey PRIMARY KEY (id);


--
-- Name: kurslar_customuser kurslar_customuser_phone_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_customuser
    ADD CONSTRAINT kurslar_customuser_phone_key UNIQUE (phone);


--
-- Name: kurslar_customuser kurslar_customuser_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_customuser
    ADD CONSTRAINT kurslar_customuser_pkey PRIMARY KEY (id);


--
-- Name: kurslar_customuser_user_permissions kurslar_customuser_user__customuser_id_permission_f868c86c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_customuser_user_permissions
    ADD CONSTRAINT kurslar_customuser_user__customuser_id_permission_f868c86c_uniq UNIQUE (customuser_id, permission_id);


--
-- Name: kurslar_customuser_user_permissions kurslar_customuser_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_customuser_user_permissions
    ADD CONSTRAINT kurslar_customuser_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: kurslar_finaltestattempt kurslar_finaltestattempt_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_finaltestattempt
    ADD CONSTRAINT kurslar_finaltestattempt_pkey PRIMARY KEY (id);


--
-- Name: kurslar_finaltestquestion kurslar_finaltestquestion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_finaltestquestion
    ADD CONSTRAINT kurslar_finaltestquestion_pkey PRIMARY KEY (id);


--
-- Name: kurslar_lesson kurslar_lesson_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_lesson
    ADD CONSTRAINT kurslar_lesson_pkey PRIMARY KEY (id);


--
-- Name: kurslar_lessonresource kurslar_lessonresource_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_lessonresource
    ADD CONSTRAINT kurslar_lessonresource_pkey PRIMARY KEY (id);


--
-- Name: kurslar_module kurslar_module_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_module
    ADD CONSTRAINT kurslar_module_pkey PRIMARY KEY (id);


--
-- Name: kurslar_testattempt kurslar_testattempt_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_testattempt
    ADD CONSTRAINT kurslar_testattempt_pkey PRIMARY KEY (id);


--
-- Name: kurslar_testquestion kurslar_testquestion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_testquestion
    ADD CONSTRAINT kurslar_testquestion_pkey PRIMARY KEY (id);


--
-- Name: kurslar_uploadedmedia kurslar_uploadedmedia_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_uploadedmedia
    ADD CONSTRAINT kurslar_uploadedmedia_pkey PRIMARY KEY (id);


--
-- Name: kurslar_userprogress kurslar_userprogress_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_userprogress
    ADD CONSTRAINT kurslar_userprogress_pkey PRIMARY KEY (id);


--
-- Name: kurslar_userprogress kurslar_userprogress_user_id_lesson_id_02d294d6_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_userprogress
    ADD CONSTRAINT kurslar_userprogress_user_id_lesson_id_02d294d6_uniq UNIQUE (user_id, lesson_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: django_site_domain_a2e37b91_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_site_domain_a2e37b91_like ON public.django_site USING btree (domain varchar_pattern_ops);


--
-- Name: kurslar_certificate_certificate_id_e2c1314b_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX kurslar_certificate_certificate_id_e2c1314b_like ON public.kurslar_certificate USING btree (certificate_id varchar_pattern_ops);


--
-- Name: kurslar_certificate_course_id_77a6a8f5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX kurslar_certificate_course_id_77a6a8f5 ON public.kurslar_certificate USING btree (course_id);


--
-- Name: kurslar_certificate_user_id_fca1e9c8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX kurslar_certificate_user_id_fca1e9c8 ON public.kurslar_certificate USING btree (user_id);


--
-- Name: kurslar_customuser_groups_customuser_id_a4a11e27; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX kurslar_customuser_groups_customuser_id_a4a11e27 ON public.kurslar_customuser_groups USING btree (customuser_id);


--
-- Name: kurslar_customuser_groups_group_id_e4de32b2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX kurslar_customuser_groups_group_id_e4de32b2 ON public.kurslar_customuser_groups USING btree (group_id);


--
-- Name: kurslar_customuser_phone_25614260_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX kurslar_customuser_phone_25614260_like ON public.kurslar_customuser USING btree (phone varchar_pattern_ops);


--
-- Name: kurslar_customuser_user_permissions_customuser_id_49290375; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX kurslar_customuser_user_permissions_customuser_id_49290375 ON public.kurslar_customuser_user_permissions USING btree (customuser_id);


--
-- Name: kurslar_customuser_user_permissions_permission_id_cb30f745; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX kurslar_customuser_user_permissions_permission_id_cb30f745 ON public.kurslar_customuser_user_permissions USING btree (permission_id);


--
-- Name: kurslar_finaltestattempt_course_id_4c679cf7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX kurslar_finaltestattempt_course_id_4c679cf7 ON public.kurslar_finaltestattempt USING btree (course_id);


--
-- Name: kurslar_finaltestattempt_user_id_0adabf2f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX kurslar_finaltestattempt_user_id_0adabf2f ON public.kurslar_finaltestattempt USING btree (user_id);


--
-- Name: kurslar_finaltestquestion_course_id_939dc5c8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX kurslar_finaltestquestion_course_id_939dc5c8 ON public.kurslar_finaltestquestion USING btree (course_id);


--
-- Name: kurslar_lesson_course_id_2200df56; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX kurslar_lesson_course_id_2200df56 ON public.kurslar_lesson USING btree (course_id);


--
-- Name: kurslar_lesson_module_id_28eb6e51; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX kurslar_lesson_module_id_28eb6e51 ON public.kurslar_lesson USING btree (module_id);


--
-- Name: kurslar_lessonresource_lesson_id_58336cca; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX kurslar_lessonresource_lesson_id_58336cca ON public.kurslar_lessonresource USING btree (lesson_id);


--
-- Name: kurslar_module_course_id_066720c2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX kurslar_module_course_id_066720c2 ON public.kurslar_module USING btree (course_id);


--
-- Name: kurslar_testattempt_lesson_id_0681bf07; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX kurslar_testattempt_lesson_id_0681bf07 ON public.kurslar_testattempt USING btree (lesson_id);


--
-- Name: kurslar_testattempt_user_id_d1e1039c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX kurslar_testattempt_user_id_d1e1039c ON public.kurslar_testattempt USING btree (user_id);


--
-- Name: kurslar_testquestion_lesson_id_792a5437; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX kurslar_testquestion_lesson_id_792a5437 ON public.kurslar_testquestion USING btree (lesson_id);


--
-- Name: kurslar_userprogress_lesson_id_1928777e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX kurslar_userprogress_lesson_id_1928777e ON public.kurslar_userprogress USING btree (lesson_id);


--
-- Name: kurslar_userprogress_user_id_04fda44d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX kurslar_userprogress_user_id_04fda44d ON public.kurslar_userprogress USING btree (user_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_kurslar_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_kurslar_customuser_id FOREIGN KEY (user_id) REFERENCES public.kurslar_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: kurslar_certificate kurslar_certificate_course_id_77a6a8f5_fk_kurslar_course_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_certificate
    ADD CONSTRAINT kurslar_certificate_course_id_77a6a8f5_fk_kurslar_course_id FOREIGN KEY (course_id) REFERENCES public.kurslar_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: kurslar_certificate kurslar_certificate_user_id_fca1e9c8_fk_kurslar_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_certificate
    ADD CONSTRAINT kurslar_certificate_user_id_fca1e9c8_fk_kurslar_customuser_id FOREIGN KEY (user_id) REFERENCES public.kurslar_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: kurslar_customuser_groups kurslar_customuser_g_customuser_id_a4a11e27_fk_kurslar_c; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_customuser_groups
    ADD CONSTRAINT kurslar_customuser_g_customuser_id_a4a11e27_fk_kurslar_c FOREIGN KEY (customuser_id) REFERENCES public.kurslar_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: kurslar_customuser_groups kurslar_customuser_groups_group_id_e4de32b2_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_customuser_groups
    ADD CONSTRAINT kurslar_customuser_groups_group_id_e4de32b2_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: kurslar_customuser_user_permissions kurslar_customuser_u_customuser_id_49290375_fk_kurslar_c; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_customuser_user_permissions
    ADD CONSTRAINT kurslar_customuser_u_customuser_id_49290375_fk_kurslar_c FOREIGN KEY (customuser_id) REFERENCES public.kurslar_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: kurslar_customuser_user_permissions kurslar_customuser_u_permission_id_cb30f745_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_customuser_user_permissions
    ADD CONSTRAINT kurslar_customuser_u_permission_id_cb30f745_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: kurslar_finaltestattempt kurslar_finaltestatt_course_id_4c679cf7_fk_kurslar_c; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_finaltestattempt
    ADD CONSTRAINT kurslar_finaltestatt_course_id_4c679cf7_fk_kurslar_c FOREIGN KEY (course_id) REFERENCES public.kurslar_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: kurslar_finaltestattempt kurslar_finaltestatt_user_id_0adabf2f_fk_kurslar_c; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_finaltestattempt
    ADD CONSTRAINT kurslar_finaltestatt_user_id_0adabf2f_fk_kurslar_c FOREIGN KEY (user_id) REFERENCES public.kurslar_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: kurslar_finaltestquestion kurslar_finaltestque_course_id_939dc5c8_fk_kurslar_c; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_finaltestquestion
    ADD CONSTRAINT kurslar_finaltestque_course_id_939dc5c8_fk_kurslar_c FOREIGN KEY (course_id) REFERENCES public.kurslar_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: kurslar_lesson kurslar_lesson_course_id_2200df56_fk_kurslar_course_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_lesson
    ADD CONSTRAINT kurslar_lesson_course_id_2200df56_fk_kurslar_course_id FOREIGN KEY (course_id) REFERENCES public.kurslar_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: kurslar_lesson kurslar_lesson_module_id_28eb6e51_fk_kurslar_module_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_lesson
    ADD CONSTRAINT kurslar_lesson_module_id_28eb6e51_fk_kurslar_module_id FOREIGN KEY (module_id) REFERENCES public.kurslar_module(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: kurslar_lessonresource kurslar_lessonresource_lesson_id_58336cca_fk_kurslar_lesson_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_lessonresource
    ADD CONSTRAINT kurslar_lessonresource_lesson_id_58336cca_fk_kurslar_lesson_id FOREIGN KEY (lesson_id) REFERENCES public.kurslar_lesson(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: kurslar_module kurslar_module_course_id_066720c2_fk_kurslar_course_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_module
    ADD CONSTRAINT kurslar_module_course_id_066720c2_fk_kurslar_course_id FOREIGN KEY (course_id) REFERENCES public.kurslar_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: kurslar_testattempt kurslar_testattempt_lesson_id_0681bf07_fk_kurslar_lesson_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_testattempt
    ADD CONSTRAINT kurslar_testattempt_lesson_id_0681bf07_fk_kurslar_lesson_id FOREIGN KEY (lesson_id) REFERENCES public.kurslar_lesson(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: kurslar_testattempt kurslar_testattempt_user_id_d1e1039c_fk_kurslar_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_testattempt
    ADD CONSTRAINT kurslar_testattempt_user_id_d1e1039c_fk_kurslar_customuser_id FOREIGN KEY (user_id) REFERENCES public.kurslar_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: kurslar_testquestion kurslar_testquestion_lesson_id_792a5437_fk_kurslar_lesson_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_testquestion
    ADD CONSTRAINT kurslar_testquestion_lesson_id_792a5437_fk_kurslar_lesson_id FOREIGN KEY (lesson_id) REFERENCES public.kurslar_lesson(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: kurslar_userprogress kurslar_userprogress_lesson_id_1928777e_fk_kurslar_lesson_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_userprogress
    ADD CONSTRAINT kurslar_userprogress_lesson_id_1928777e_fk_kurslar_lesson_id FOREIGN KEY (lesson_id) REFERENCES public.kurslar_lesson(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: kurslar_userprogress kurslar_userprogress_user_id_04fda44d_fk_kurslar_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kurslar_userprogress
    ADD CONSTRAINT kurslar_userprogress_user_id_04fda44d_fk_kurslar_customuser_id FOREIGN KEY (user_id) REFERENCES public.kurslar_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict spTXnpfcyI0JlSNiNdWepWVJ5aeWG4EhhxDTjt9is77X6BOZaluGf8UuywIyU8d

